### ISSUE TITLE
Contiguous time ranges can produce slightly wrong answers.

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#140]
That is, if we have two contiguous time ranges [t0,t1] and [t2,t3], then [t0,t1]+[t2,t3] != [t0,t3]. I think that the issue is that the BETWEEN in SQL is fully inclusive of the range. We'll need to treat it more subtly in order to make sure that we're not slightly over or undercounting events in these cases.

**Comment by cmillion** [comment]
I'm disabling memlight in image creation (as of v1.24.0) until this is resolved. (Though it will also effect light curves.)

**Comment by cmillion** [comment]
It will also be an issue for movies.

**Comment by bshiao** [comment]
Between in sql is definitely inclusive of range, https://msdn.microsoft.com/en-us/library/ms187922(v=sql.110).aspx,

“where time between 10 and 20” is identical to “where time >= 10 and time <=20”, there are arguments for using both on the blogs, using either in our situation is fine whatever makes the most sense, there’s no performance difference. I prefer to use between because it’s less typing and I won’t accidently forget an “=” sign.

Bernie

**Comment by cmillion** [comment]
Yeah. I went down that same blog hole last night while looking into this. I think that we should probably standardize everything as [x,y), but we should discuss at the telecon.

The effect on actual results is very, very small, so I don't think we need to rush out a fix for beta.

**Comment by cmillion** [comment]
For consistency, we have agreed that all time range searches will be inclusive of the start time and exclusive of the end time. [t0,t1)

We're pretty sure that all of these changes are on the Python side (mostly in gQuery.py), and this will be assigned to v1.24.5.

**Comment by cmillion** [comment]
Per bshiao, the following database functions were also revised:

create_fGetFNUVShutter.sql
create_fGetNearbyAspectXYZ.sql
create_fGetNearbyObjEqCountFUV.sql
create_fGetNearbyObjEqCountNUV.sql
create_fGetNearbyObjEqFUV.sql
create_fGetNearbyObjEqFUVAllColumns.sql
create_fGetNearbyObjEqNUV.sql
create_fGetNearbyObjEqNUVAllColumns.sql
create_fGetObjFromRectFUVAllColumns.sql
create_fGetObjFromRectNUVAllColumns.sql
