### ISSUE TITLE
move shutter correction back into the database

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#156]
The shutter correction being done by the database was wrong, so I moved that onto the client side in 1.25.0. I download all unique time stamps within the time range, order them by time, then subtract each time from the one following it in order. Values in the resulting array of more than 0.05 are considered "shuttered." This works great, if a little slowly, but some reasonable queries for full depth observations always time out. e.g. `http://masttest.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select distinct t from (select time as t from GPFCore.dbo.NUVPhotonsV where time >= 834413879995 and time < 834415472995 union all select time as t from GPFCore.dbo.NUVPhotonsNULLV where time >= 834413879995 and time < 834415472995) x -- 1437015198&format=json&timeout={}`

So shutter needs to be moved back into the database.

**Comment by cmillion** [comment]
I'll test the limits of my SQL-fu to see if I can construct an SQL query that performs the described operation.

**Comment by bshiao** [comment]
that would be great, I'll have to back and see what I did wrong, I'm sure I can still build a much smaller table that we can use so we don't have run queries like you have above each time, those still be slower than we'd like.

**Comment by bshiao** [comment]
I built a test table that represents the array you mentioned above for those time boundaries.
when you say "Values in the resulting array of more than 0.05 are considered "shuttered."". does that mean the count of rows in the array where the value is more than 0.05 is the "shutter" value, in this case there were none. But if you had say 5 rows > 0.05, what happens then, do you just return that as the result back to the python code or should there be more processing in the DB?

**Comment by cmillion** [comment]
If there were 5 rows >0.05, I would ideally return the number 5*0.05 = .25, which is the amount of time in seconds that is "shuttered" and should be subtracted from the raw exposure time.

It would be slightly more complicated but slightly better to have the 0.05 as an adjustable parameter T and return the number of rows N > T so that the shutter was N * T. This is because the choice of 0.05 for the shutter threshold is kind of arbitrary, as far as I can tell; but I also can't imagine ever wanting or needing to change it.

**Comment by bshiao** [comment]
Ok, this is what I’ve done so far, using the example you gave below.

“select distinct t from (select time as t from GPFCore.dbo.NUVPhotonsV where time >= 834413879995 and time < 834415472995 union all select time as t from GPFCore.dbo.NUVPhotonsNULLV where time >= 834413879995 and time < 834415472995) x”

I built a test table using the following code, I slightly modified the end condition to be <=834415472995 so I would have that one last row to subtract 5 from.


create table NUVShutterTest (time bigint, deltaTime bigint, rowNumber bigint identity(1,1))

insert into NUVShutterTest (time)
select distinct t from (select time as t from GPFCore.dbo.NUVPhotonsV where time >= 834413879995 and time <= 834415472995
union all
select time as t from GPFCore.dbo.NUVPhotonsNULLV where time >= 834413879995 and time <= 834415472995) x
order by t
-- (318601 row(s) affected)

-- query to check that I’m doing what you described

select top 100 n.time as nTime, n2.time as n2Time, n2.time-n.time as deltaTime, n.rowNumber as nRowNUmber, n2.rowNumber as n2RowNumber
from NUVShutterTest as n
inner join NUVShutterTest as n2 on n.rowNumber+1=n2.rowNumber
order by n.rowNumber

-- do the actual update
update n
set deltaTime=n2.time-n.time
from NUVShutterTest as n
inner join NUVShutterTest as n2 on n.rowNumber+1=n2.rowNumber

and then the query that does the actual shutter calculation

select 0.05*count(time) from NUVShutterTest
where deltaTime is not null
and deltaTime > 5
and time >= 834413879995 and time < 834415472995
-- returns 0.0 in this case

Is this correct for shutter calculation above?

So the shutter function call would be something like the following.

Select dbo.fGetFUVShutter(834413879995, 834415472995, delta)
Where delta is as you described below, but in the default case is 5

So I’ve already built the FUV table, all it contains so far is the distinct time values, I’m going to go ahead and calculate the deltas if all looks good.

Ok, so, we talked about flags a bit, does it matter? I built the FUV table with is essentially the following query but broken up into time slices because it’s too many rows to put into FUVShutter in one query. There is no flag cut though, should there be one? One thought I had is, what if for a distinct time value all the photons associated with it have a flag != 0, should that time value be inserted into FUVShutter? I didn’t quite understand your point during the telecon about the ranges, could you elaborate?

insert into FUVShutter (time)
select distinct t from (select time as t from GPFCore.dbo.FUVPhotonsVunion all
select time as t from GPFCore.dbo.FUVPhotonsNULLV) as x
order by t

**Comment by bshiao** [comment]
one other comment, based upon how the [FN]UVShutter tables are going to be pre-computed there will of course be large delta values between eclipses. Is the presumption that queries would never have time boundaries that would span eclipses or should I somehow detect the eclipse boundaries from the data and make those delta values = 0 or null

**Comment by bshiao** [comment]
I've created the necessary pre-computed table and function for FUV to support shutter.

-- sample urls that one can test in the browser

-- returns the count of rows
http://masttest.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select count(*) as theCount from GPFCore.dbo.FUVShutterPOTimeV where time >= 834413879995 and time < 834415472995&format=json&timeout={}

-- returns the contents of FUVShutterPOTimeV in time order
-- essentially this is what you're doing now, only now it'll also return
-- the deltaTime as another column
http://masttest.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select * from GPFCore.dbo.FUVShutterPOTimeV where time >= 834413879995 and time < 834415472995 order by time&format=json&timeout={}


-- here's a sample call to the new function, it takes timeStart, timeEnd and deltaTime max, usually 5.
-- what's curious is that the above query returns many rows where the delta is > 5, why is that?
-- the function returns 0.05*count of rows where delta > deltaTimeMax and the number of rows that
-- met that criteria as a validation check.
-- one strange things is for the 2nd url below almost all of the FUV rows have delta's 
-- between times > 5, why would that be, for the same time range in NUV the shutter was 0 I believe.

http://masttest.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select * from GPFCore.dbo.fGetFUVShutter(834413879995,834415472995,5)&format=json&timeout={}

**Comment by cmillion** [comment]
Will respond to other items noted above, but here is a description of the edge case I thought of:
* If either the t0 or t1 times bisect a period of "shutter" then the returned value should only consider the overlap. That is, if the time bin is [t0,t1] and there is a shutter period over [t0',t1'] such that in time order they are t0',t0,t1',t1, then the shutter should correct for [t0,t1']. This covers the case where the time boundary is between eclipses. My proposal is that when you compile the ordered list of unique timestamps, include t0 and t1 as the first and last entries. But I think this precludes the use of a precomputed table...

**Comment by cmillion** [comment]
In response to: "What's curious is that the above query returns many rows where the delta is >5, why is that? [...]" I do not know, and I think it's in error. When I request the shutter from the same time range in FUV using dbasetools.compute_shutter(), I get a return of zero.

**Comment by bshiao** [comment]
Ok, I double checked this, I’m either not seeing it or something else is wrong. See the following code.

drop table FUVShutterTest
create table FUVShutterTest (time bigint, deltaTime bigint, rowNumber bigint identity(1,1))


insert into FUVShutterTest (time)
select distinct t from (select time as t from GPFCore.dbo.FUVPhotonsV where time >= 834413879995 and time <= 834415472995
union all
select time as t from GPFCore.dbo.FUVPhotonsNULLV where time >= 834413879995 and time <= 834415472995) x
order by t
-- (121686 row(s) affected)


update n
set deltaTime=n2.time-n.time
from FUVShutterTest as n
inner join FUVShutterTest as n2 on n.rowNumber+1=n2.rowNumber

-- shutter query
select 0.05*count(time) from FUVShutterTest
where deltaTime is not null
and deltaTime > 5
-- 6074.35

-- take a look at the data, ordering by rownumber or time should be equivalent
-- many values where deltaTime > 5 ?????
select * from FUVShutterTest
order by rowNumber

FUVShutterTest has an identity attribute so that rowNumber is increasing by 1 as rows are inserted and since they are ordered by time rowNumber increases by 1 for each greater time value.

The deltaTime is then calculated using the update above based upon the following.

“download all unique time stamps within the time range, order them by time, then subtract each time from the one following it in order.
Values in the resulting array of more than 0.05 are considered "shuttered."”

Can you take another look something isn’t right somewhere?

**Comment by cmillion** [comment]
So, we found a few problems with my shutter algorithm that got corrected last night in the v1.26.0 branch. They are:

1. I'd previously said that it should use both NULL and non-NULL data. This is wrong. It should only use non-NULL data.
2. It must take into account bin boundaries that occur in the middle of a "shutter" period. For example by including the bin boundaries as "event" times in the sorted list of unique event times.
3. I'd said that you multiply the number of gaps >= 0.05 s by 0.05 s. You should actually add up the duration of all gaps >= 0.05 s. (That seems obvious now!)

**Comment by cmillion** [comment]
Update: There's a new database table containing every unique photon time being built. This will make these queries a lot faster. The actual computations from there (as outlined in 1/2/3 above) will remain on the client side for now (v1.26.0), as the actual computations are fairly quick in numpy and the new extjs query handling (issue #170) is reducing lost effort (on the database side) from longer queries.
