### ISSUE TITLE
gMap's --trange should accept format [t0,t1] but only accepts format [[t0,t1]]

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#160]
The former results in an error. It is handling --trange identical to --tranges.

**Comment by cmillion** [comment]
@scfleming I am unable to reproduce this behavior. The command below produces the expected behavior for me. Can you confirm that this is what you meant?

gMap -b 'FUV' --skypos [10.6833,41.2692] --skyrange [0.1,0.1] --count 'm31.fits' -v 2 --overwrite --coadd --trange [746828461.995,746830089.995] --memlight 20

**Comment by scfleming** [comment]
I think it only breaks for movies, try running with a stepsize and output a movie file?

**Comment by cmillion** [comment]
The following command runs without error, but does not output a three dimensional FITS "movie" as expected.

./gMap -b 'FUV' --skypos [10.6833,41.2692] --skyrange [0.1,0.1] --count 'm31.fits' -v 2 --overwrite --coadd --trange [746828461.995,746830089.995] --memlight 20 -s 100

**Comment by scfleming** [comment]
The error I was having was here, where "tranges" was just a single list of [t0,t1], so in the "for trange in tranges" part it was iterating over each element in a list, rather than each list inside a larger list (which you would get if you specified trange=[[ta,tb], [tc,td]], etc.

Also, I am running by importing gMap into another .py file, not from command line (in case that matters)

def movie_tbl(band,tranges,verbose=0,framesz=0,retries=20):
	"""Initialize a FITS table to contain movie frame information."""
	if verbose:
		mc.print_inline('Populating exposure time table.')
	tstarts,tstops,exptimes=[],[],[]
	for trange in tranges:

**Comment by cmillion** [comment]
Oh. Yes. Ok. I bet there's a check_args() that makes this work fine from the command line but needs to be moved inside of the main function.

**Comment by scfleming** [comment]
Probably.  Also has an issue here in def movie()

else:
		for trange in tranges:
			stepsz = framesz if framesz else trange[1]-trange[0]

Suspect doing the sanity check to put a single list inside its own list from check_args() into main gMap will fix all this.
