### ISSUE TITLE
Add a new flag bitmask warning users if a known MCAT source lies within the aperture/annulus.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#247]
Include consideration for "PSF" extension, i.e., if the MCAT source is close enough that wings would substantially impact the flux measurements.

**Comment by cmillion** [comment]
Maybe optionally flag based upon relatively brightness of the MCAT source vs. whatever is in the annulus, as a function of, e.g., % contribution.

**Comment by cmillion** [comment]
Two questions:
(1) What should we use as the distance between the target location and any MCAT source at which we determine that the MCAT source is _not_ the source of interest?
(2) Rather than a flag, I'm thinking about adding a new column to the lightcurve file that records the MCAT magnitude of the brightest contaminating source (if one exists). Then users can decide for themselves whether that's bright enough to matter. Thoughts?

**Comment by cmillion** [comment]
I could also do columns for (a) brightest nearby MCAT source + (b) distance from target location. That sort of solves (1), I think.

**Comment by scfleming** [comment]
It will be hard to generalize question 1 for all use cases.  Would it be avoided if, instead, we only flag if a known source is between the inner and outer annuli, i.e., your background contains some source?  Because *that* should almost never be desired, whereas in most cases we might expect at least one source inside the aperture.  So, change the title of this ticket to "warn user if a known source is within the background annulus".

**Comment by scfleming** [comment]
In terms of question 2, this is another example of a scalar that we'd want to put as some sort of header to the light curve output.  I'm wondering if we should have our output files be FITS files instead of ASCII at this point.  Then we could put useful scalar info in the header and the light curve columns as binary table.

**Comment by cmillion** [comment]
Although two sources in your aperture is also a cause for concern. Is flagging the distance to the nearest bright source not a good general solution to (1)?

**Comment by scfleming** [comment]
For within the aperture, instead of distance, how about just a count?  If the count is 1 (often the case) then you're probably fine.  If > 1, probably want to look at things more carefully.

**Comment by cmillion** [comment]
So new columns are:
1. num. of MCAT sources within the aperture
2. num. of MCAT sources within the annulus
3. magnitude of brightest MCAT source contaminating the annulus

**Comment by scfleming** [comment]
Sounds good to me!

**Comment by cmillion** [comment]
It _is_ a little silly to repeat those for every row, since they'll be constant for any sky position + aperture + annulus. Does make much more sense as a header value. But I think good is the enemy of done for right now, and we'll migrate it to a header value later when we implement light curve file headers.

**Comment by cmillion** [comment]
It turns out that past me had already implemented a data structure that recorded all of this useful information that doesn't change on a per-bin basis. So I went ahead and implemented it as the content of an optional header for the lightcurve files. `addhdr` should also now work when calling as a Python module (except it doesn't record the CL syntax, since there was none in that case).
