### ISSUE TITLE
Network timeouts result in lost effort.

### ISSUE THREAD

**Issue by cmillion** [cmillion/gPhoton#6]
Especially in gAperture. It needs to at least write as it goes. There should probably be some way to "resume" a run interrupted by a network outage.

**Comment by scfleming** [comment]
Will this largely be solved with the change to handle the extJS parameter and improved functionality of retry option?

**Comment by cmillion** [comment]
I expect timeouts to become extremely rare (although I'm still tweaking manage_requests). But if your connection just goes down in the middle of a run, you'll still lose all of your effort. The solution I had in mind for this was to either write information to the .csv on the fly (as I do for some of the calibration scripts) or to do a temporary local cache of some of the larger query results (like the photon lists). The latter would be easier once (and if) we supported direct ingest of photon list files. But both would require substantial refactoring.

I find that it's only still a problem on the deepest fields or for large gMap images.

**Comment by scfleming** [comment]
Another (distant) improvement could be to write a function that will simply ping to see if there is internet connection at all (pinging an IP address, or google.com for example), so that it can distinguish between not getting back a result from the gPhoton server (increase retry count) vs. having a network cable unplugged (shouldn't count that against the server).  This could be a rabbit hole, but something simple might be of some use when, e.g., reporting an error as to why something timed out maybe...

**Comment by cmillion** [comment]
Yeah. Not a bad idea. I can add that in as an additional test for when a query simply fails to return anything after some number of retries. If it looks like it's a local connectivity issue, then, it can print a warning to that effect. Could cut down on possibility of needing to field user questions about database availability when it's really on the client side.

**Comment by cmillion** [comment]
The recent extjs() changes (issue #170) have made timeouts rare. Sub-elements of this have been moved to issue #183 and #182.
